---
- name: Setup Arch Linux
  hosts: localhost
  become: yes
  vars:
    ansible_user: khtodod
    ansible_user_id: khtodod
    ssh_public_key: "{{ lookup('ansible.vault', 'ssh_key.vault') }}"

  tasks:
    - name: Update package database and upgrade system
      pacman:
        update_cache: yes
        upgrade: yes

    - name: Install base packages
      pacman:
        name:
          - git
          - openssh
          - neovim
          - zsh
          - docker
          - mysql
          - go
          - lightdm
          - lightdm-gtk-greeter # Optional display manager
          - yarn
        state: present

    # Install yay AUR helper
    - name: Install dependencies for building yay
      pacman:
        name:
          - base-devel
          - git
        state: present

    - name: Clone yay AUR helper repository
      git:
        repo: https://aur.archlinux.org/yay.git
        dest: /home/{{ ansible_user_id }}/yay

    - name: Build and install yay
      shell: |
        cd /home/{{ ansible_user_id }}/yay
        makepkg -si --noconfirm
      args:
        chdir: /home/{{ ansible_user_id }}/yay
        creates: /usr/bin/yay

    - name: Clone dwm repository
      git:
        repo: https://git.suckless.org/dwm
        dest: /usr/local/src/dwm

    - name: Compile and install dwm
      shell: |
        cd /usr/local/src/dwm
        sudo make clean install
      args:
        creates: /usr/local/bin/dwm

    # Install AUR packages using yay
    - name: Install Visual Studio Code from AUR
      shell: yay -S --noconfirm visual-studio-code-bin
      args:
        executable: /bin/bash

    - name: Install Azure Data Studio from AUR
      shell: yay -S --noconfirm azure-data-studio-bin
      args:
        executable: /bin/bash

    - name: Install Steam from AUR
      shell: yay -S --noconfirm steam
      args:
        executable: /bin/bash

    - name: Install Insomnia from AUR
      shell: yay -S --noconfirm insomnia
      args:
        executable: /bin/bash

    - name: Install Spotify from AUR
      shell: yay -S --noconfirm spotify
      args:
        executable: /bin/bash

    - name: Install Discord from AUR
      shell: yay -S --noconfirm discord
      args:
        executable: /bin/bash

    - name: Install AnyDesk from AUR
      shell: yay -S --noconfirm anydesk-bin
      args:
        executable: /bin/bash

    - name: Install Thorium Browser from AUR
      shell: yay -S --noconfirm thorium-bin
      args:
        executable: /bin/bash

    - name: Install GitHub CLI from AUR
      shell: yay -S --noconfirm github-cli
      args:
        executable: /bin/bash

    # Enable Docker service
    - name: Enable Docker service
      systemd:
        name: docker
        enabled: yes
        state: started

    - name: Add user to Docker group
      user:
        name: "{{ ansible_user_id }}"
        groups: docker
        append: yes

    # Start and enable MySQL service
    - name: Start and enable MySQL service
      systemd:
        name: mysqld
        enabled: yes
        state: started

    - name: Secure MySQL installation
      shell: |
        mysql -u root -e "UPDATE mysql.user SET Password = PASSWORD('root') WHERE User = 'root';"
        mysql -u root -p'root' -e "DELETE FROM mysql.user WHERE User='';"
        mysql -u root -p'root' -e "DROP DATABASE IF EXISTS test;"
        mysql -u root -p'root' -e "FLUSH PRIVILEGES;"
      args:
        executable: /bin/bash

    - name: Install PHP extensions
      shell: |
        pecl install apcu
        pecl install xdebug
      args:
        executable: /bin/bash

    - name: Ensure PHP-FPM service is started and enabled
      systemd:
        name: php-fpm
        enabled: yes
        state: started

    - name: Enable SSH service
      systemd:
        name: sshd
        enabled: yes
        state: started

    - name: Enable LightDM service
      systemd:
        name: lightdm
        enabled: yes
        state: started

    - name: Create .xinitrc file to start DWM
      copy:
        content: "exec dwm\n"
        dest: /home/{{ ansible_user_id }}/.xinitrc
        owner: "{{ ansible_user_id }}"
        group: "{{ ansible_user_id }}"
        mode: "0644"

    - name: Ensure .xinitrc is executable
      file:
        path: /home/{{ ansible_user_id }}/.xinitrc
        mode: "0755"

    - name: Install Oh My Zsh
      shell: |
        sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" || true
      args:
        creates: /home/{{ ansible_user_id }}/.oh-my-zsh

    - name: Enable Docker service
      systemd:
        name: docker
        enabled: yes
        state: started

    - name: Add user to Docker group
      user:
        name: "{{ ansible_user_id }}"
        groups: docker
        append: yes

    - name: Start and enable MySQL service
      systemd:
        name: mysqld
        enabled: yes
        state: started

    - name: Secure MySQL installation
      mysql_user:
        name: root
        host_all: yes
        password: "root"
        priv: "*.*:ALL,GRANT"
        state: present

    - name: Ensure SSH directory exists for user
      file:
        path: /home/{{ ansible_user_id }}/.ssh
        state: directory
        mode: "0700"
        owner: "{{ ansible_user_id }}"
        group: "{{ ansible_user_id }}"

    - name: Add your SSH public key to authorized_keys
      authorized_key:
        user: "{{ ansible_user_id }}"
        state: present
        key: "{{ ssh_public_key }}"
        path: /home/{{ ansible_user_id }}/.ssh/authorized_keys

    - name: Ensure Neovim config directory exists
      file:
        path: /home/{{ ansible_user_id }}/.config/nvim
        state: directory
        mode: "0755"
        owner: "{{ ansible_user_id }}"
        group: "{{ ansible_user_id }}"

    - name: Copy Neovim init.vim configuration file
      copy:
        src: nvim_config/init.vim
        dest: /home/{{ ansible_user_id }}/.config/nvim/init.vim
        owner: "{{ ansible_user_id }}"
        group: "{{ ansible_user_id }}"
        mode: "0644"

    - name: Copy Neovim coc-settings.json configuration file
      copy:
        src: nvim_config/coc-settings.json
        dest: /home/{{ ansible_user_id }}/.config/nvim/coc-settings.json
        owner: "{{ ansible_user_id }}"
        group: "{{ ansible_user_id }}"
        mode: "0644"

    - name: Download NVM install script
      get_url:
        url: https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.5/install.sh
        dest: /home/{{ ansible_user_id }}/install-nvm.sh
        mode: "0755"

    - name: Install NVM
      shell: bash /home/{{ ansible_user_id }}/install-nvm.sh
      args:
        creates: /home/{{ ansible_user_id }}/.nvm

    - name: Load NVM and install Node.js (v22)
      shell: |
        export NVM_DIR="$HOME/.nvm"
        [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
        nvm install 22
      args:
        executable: /bin/bash

    - name: Set Node.js v22 as default
      shell: |
        export NVM_DIR="$HOME/.nvm"
        [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
        nvm alias default 22
      args:
        executable: /bin/bash

    # Install Rust toolchain
    - name: Download Rust installation script
      get_url:
        url: https://sh.rustup.rs
        dest: /home/{{ ansible_user_id }}/install-rust.sh
        mode: "0755"

    - name: Install Rust toolchain
      shell: bash /home/{{ ansible_user_id }}/install-rust.sh -y
      args:
        creates: /home/{{ ansible_user_id }}/.cargo/bin/rustc

    - name: Source Cargo environment and install components
      shell: |
        source $HOME/.cargo/env
        rustup component add rls rust-analysis rust-src
      args:
        executable: /bin/bash

    # Install Go language server (gopls)
    - name: Install Go language server (gopls)
      shell: |
        export PATH=$PATH:/usr/local/go/bin
        go install golang.org/x/tools/gopls@latest
      args:
        creates: /home/{{ ansible_user_id }}/go/bin/gopls

    # Set Thorium as the default browser
    - name: Set Thorium as default browser
      shell: |
        xdg-settings set default-web-browser thorium-browser.desktop
      args:
        executable: /bin/bash

    # Authorize GitHub CLI
    - name: GitHub CLI authentication
      shell: |
        gh auth login --with-token
      args:
        executable: /bin/bash
      register: gh_auth
      ignore_errors: yes

    - name: Print GitHub CLI authentication result
      debug:
        var: gh_auth
