---
- name: Setup Arch Linux
  hosts: localhost
  become: yes
  vars:
    ssh_public_key: "{{ lookup('ansible.vault', 'ssh_key.vault') }}"

  tasks:
    - name: Update package database and upgrade system
      pacman:
        update_cache: yes
        upgrade: yes

    - name: Install base packages
      pacman:
        name:
          - git
          - openssh
          - neovim
          - zsh
          - docker
          - mysql
          - go
          - dwm
          - lightdm
          - lightdm-gtk-greeter # Optional display manager
          - yarn # Yarn (This can be installed through the Arch repository)
        state: present

    # Install Visual Studio Code from source
    - name: Clone Visual Studio Code repository
      git:
        repo: https://github.com/microsoft/vscode.git
        dest: /usr/local/src/vscode
        version: main

    - name: Build and install Visual Studio Code
      shell: |
        cd /usr/local/src/vscode
        yarn
        yarn compile
        yarn build
        cp .build/vscode /usr/local/bin/code
      args:
        creates: /usr/local/bin/code

    # Install Azure Data Studio from source
    - name: Clone Azure Data Studio repository
      git:
        repo: https://github.com/microsoft/azuredatastudio.git
        dest: /usr/local/src/azuredatastudio
        version: main

    - name: Build and install Azure Data Studio
      shell: |
        cd /usr/local/src/azuredatastudio
        yarn
        yarn compile
        yarn build
        cp .build/azuredatastudio /usr/local/bin/azuredatastudio
      args:
        creates: /usr/local/bin/azuredatastudio

    # Install Steam (Steam is typically installed from the AUR, but if you want to build it yourself):
    - name: Install Steam from AUR using yay
      aur:
        name: steam
        state: present
        use: yay

    # Install Insomnia from source
    - name: Clone Insomnia repository
      git:
        repo: https://github.com/Kong/insomnia.git
        dest: /usr/local/src/insomnia
        version: develop

    - name: Build and install Insomnia
      shell: |
        cd /usr/local/src/insomnia
        yarn
        yarn build
        cp build/linux/insomnia /usr/local/bin/insomnia
      args:
        creates: /usr/local/bin/insomnia

    # Install Spotify (Spotify can be installed from AUR)
    - name: Install Spotify from AUR using yay
      aur:
        name: spotify
        state: present
        use: yay

    # Install Discord from source (alternatively, use AUR for simplicity)
    - name: Install Discord from AUR using yay
      aur:
        name: discord
        state: present
        use: yay

    # Install AnyDesk from AUR using yay
    - name: Install AnyDesk from AUR using yay
      aur:
        name: anydesk-bin
        state: present
        use: yay

    # Install Thorium Browser from source
    - name: Clone Thorium Browser repository
      git:
        repo: https://github.com/Alex313031/thorium.git
        dest: /usr/local/src/thorium
        version: main

    - name: Build and install Thorium Browser
      shell: |
        cd /usr/local/src/thorium
        ./build.sh
        cp out/thorium /usr/local/bin/thorium-browser
      args:
        creates: /usr/local/bin/thorium-browser

    # Install GitHub CLI from source
    - name: Clone GitHub CLI repository
      git:
        repo: https://github.com/cli/cli.git
        dest: /usr/local/src/cli
        version: main

    - name: Build and install GitHub CLI
      shell: |
        cd /usr/local/src/cli
        make
        cp bin/gh /usr/local/bin/gh
      args:
        creates: /usr/local/bin/gh

    # Enable Docker service
    - name: Enable Docker service
      systemd:
        name: docker
        enabled: yes
        state: started

    - name: Add user to Docker group
      user:
        name: "{{ ansible_user }}"
        groups: docker
        append: yes

    # Start and enable MySQL service
    - name: Start and enable MySQL service
      systemd:
        name: mysqld
        enabled: yes
        state: started

    - name: Secure MySQL installation
      shell: |
        mysql -u root -e "UPDATE mysql.user SET Password = PASSWORD('root') WHERE User = 'root';"
        mysql -u root -p'root' -e "DELETE FROM mysql.user WHERE User='';"
        mysql -u root -p'root' -e "DROP DATABASE IF EXISTS test;"
        mysql -u root -p'root' -e "FLUSH PRIVILEGES;"
      args:
        executable: /bin/bash

    - name: Install PHP extensions
      shell: |
        pecl install apcu
        pecl install xdebug
      args:
        executable: /bin/bash

    - name: Ensure PHP-FPM service is started and enabled
      systemd:
        name: php-fpm
        enabled: yes
        state: started

    - name: Enable SSH service
      systemd:
        name: sshd
        enabled: yes
        state: started

    - name: Enable LightDM service
      systemd:
        name: lightdm
        enabled: yes
        state: started

    - name: Create .xinitrc file to start DWM
      copy:
        content: "exec dwm\n"
        dest: /home/{{ ansible_user_id }}/.xinitrc
        owner: "{{ ansible_user_id }}"
        group: "{{ ansible_user_id }}"
        mode: "0644"

    - name: Ensure .xinitrc is executable
      file:
        path: /home/{{ ansible_user_id }}/.xinitrc
        mode: "0755"

    - name: Install Oh My Zsh
      shell: |
        sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" || true
      args:
        creates: /home/{{ ansible_user_id }}/.oh-my-zsh

    - name: Enable Docker service
      systemd:
        name: docker
        enabled: yes
        state: started

    - name: Add user to Docker group
      user:
        name: "{{ ansible_user_id }}"
        groups: docker
        append: yes

    - name: Start and enable MySQL service
      systemd:
        name: mysqld
        enabled: yes
        state: started

    - name: Secure MySQL installation
      mysql_user:
        name: root
        host_all: yes
        password: "root"
        priv: "*.*:ALL,GRANT"
        state: present

    - name: Ensure SSH directory exists for user
      file:
        path: /home/{{ ansible_user_id }}/.ssh
        state: directory
        mode: "0700"
        owner: "{{ ansible_user_id }}"
        group: "{{ ansible_user_id }}"

    - name: Add your SSH public key to authorized_keys
      authorized_key:
        user: "{{ ansible_user_id }}"
        state: present
        key: "{{ ssh_public_key }}"
        path: /home/{{ ansible_user_id }}/.ssh/authorized_keys

    - name: Ensure Neovim config directory exists
      file:
        path: /home/{{ ansible_user_id }}/.config/nvim
        state: directory
        mode: "0755"
        owner: "{{ ansible_user_id }}"
        group: "{{ ansible_user_id }}"

    - name: Copy Neovim init.vim configuration file
      copy:
        src: nvim_config/init.vim
        dest: /home/{{ ansible_user_id }}/.config/nvim/init.vim
        owner: "{{ ansible_user_id }}"
        group: "{{ ansible_user_id }}"
        mode: "0644"

    - name: Copy Neovim coc-settings.json configuration file
      copy:
        src: nvim_config/coc-settings.json
        dest: /home/{{ ansible_user_id }}/.config/nvim/coc-settings.json
        owner: "{{ ansible_user_id }}"
        group: "{{ ansible_user_id }}"
        mode: "0644"

    - name: Download NVM install script
      get_url:
        url: https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.5/install.sh
        dest: /home/{{ ansible_user_id }}/install-nvm.sh
        mode: "0755"

    - name: Install NVM
      shell: bash /home/{{ ansible_user_id }}/install-nvm.sh
      args:
        creates: /home/{{ ansible_user_id }}/.nvm

    - name: Load NVM and install Node.js (v22)
      shell: |
        export NVM_DIR="$HOME/.nvm"
        [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
        nvm install 22
      args:
        executable: /bin/bash

    - name: Set Node.js v22 as default
      shell: |
        export NVM_DIR="$HOME/.nvm"
        [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
        nvm alias default 22
      args:
        executable: /bin/bash

    # Install Rust toolchain
    - name: Download Rust installation script
      get_url:
        url: https://sh.rustup.rs
        dest: /home/{{ ansible_user_id }}/install-rust.sh
        mode: "0755"

    - name: Install Rust toolchain
      shell: bash /home/{{ ansible_user_id }}/install-rust.sh -y
      args:
        creates: /home/{{ ansible_user_id }}/.cargo/bin/rustc

    - name: Source Cargo environment and install components
      shell: |
        source $HOME/.cargo/env
        rustup component add rls rust-analysis rust-src
      args:
        executable: /bin/bash

    # Install Go language server (gopls)
    - name: Install Go language server (gopls)
      shell: |
        export PATH=$PATH:/usr/local/go/bin
        go install golang.org/x/tools/gopls@latest
      args:
        creates: /home/{{ ansible_user_id }}/go/bin/gopls

    # Set Thorium as the default browser
    - name: Set Thorium as default browser
      shell: |
        xdg-settings set default-web-browser thorium-browser.desktop
      args:
        executable: /bin/bash

    # Authorize GitHub CLI
    - name: GitHub CLI authentication
      shell: |
        gh auth login --with-token
      args:
        executable: /bin/bash
      register: gh_auth
      ignore_errors: yes

    - name: Print GitHub CLI authentication result
      debug:
        var: gh_auth
